In [69]:
import pandas as pd
df = pd.read_csv("flipkart.csv")
df

,star,rating,discount,price,brand,storage,processor
0,4.2,"50,094 Ratings",20% off,"₹9,999","MOTOROLA g35 5G (Guava Red, 128 GB) (4 GB RAM)",128 GB,Unisoc
1,4.5,"58,286 Ratings",22% off,"₹13,999","vivo T4x 5G (Marine Blue, 128 GB) (6 GB RAM)",128 GB,Mediatek
2,4.3,"1,66,171 Ratings",20% off,"₹11,999","Motorola g45 5G (Brilliant Blue, 128 GB) (8 G...",128 GB,Snapdragon
3,4.2,"51,771 Ratings",37% off,"₹6,249","Samsung Galaxy F05 (Twilight Blue, 64 GB) (4 ...",64 GB,Mediatek
4,4.5,"58,286 Ratings",22% off,"₹13,999","vivo T4x 5G (Pronto Purple, 128 GB) (6 GB RAM)",128 GB,Mediatek
...,...,...,...,...,...,...,...
403,4.2,"2,635 Ratings",24% off,"₹16,154","Samsung Galaxy A16 5G (Blue Black, 128 GB) (8...",128 GB,Mediatek
404,4.4,"8,969 Ratings",28% off,"₹17,999","Infinix Note 50s 5G+ (Titanium Grey, 256 GB) ...",256 GB,Mediatek
405,4.4,"26,715 Ratings",33% off,"₹19,999","Motorola Edge 50 Neo (PANTONE Poinciana, 256 G...",256 GB,Mediatek
406,4.6,"1,807 Ratings",NaN,"₹80,999","Samsung Galaxy S25 5G (Silver Shadow, 256 GB) ...",256 GB,Snapdragon
407,4.5,973 Ratings,NaN,"₹49,999","Google Pixel 9A (Obsidian, 256 GB) (8 GB RAM)",256 GB,Google

In [70]:
df.shape

(408, 7)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   star       408 non-null    float64
 1   rating     408 non-null    object
 2   discount   403 non-null    object
 3   price      408 non-null    object
 4   brand      408 non-null    object
 5   storage    408 non-null    object
 6   processor  393 non-null    object
dtypes: float64(1), object(6)
memory usage: 22.4+ KB

In [72]:
df = df.copy()
df.dropna(axis=0, inplace=True)
df

,star,rating,discount,price,brand,storage,processor
0,4.2,"50,094 Ratings",20% off,"₹9,999","MOTOROLA g35 5G (Guava Red, 128 GB) (4 GB RAM)",128 GB,Unisoc
1,4.5,"58,286 Ratings",22% off,"₹13,999","vivo T4x 5G (Marine Blue, 128 GB) (6 GB RAM)",128 GB,Mediatek
2,4.3,"1,66,171 Ratings",20% off,"₹11,999","Motorola g45 5G (Brilliant Blue, 128 GB) (8 G...",128 GB,Snapdragon
3,4.2,"51,771 Ratings",37% off,"₹6,249","Samsung Galaxy F05 (Twilight Blue, 64 GB) (4 ...",64 GB,Mediatek
4,4.5,"58,286 Ratings",22% off,"₹13,999","vivo T4x 5G (Pronto Purple, 128 GB) (6 GB RAM)",128 GB,Mediatek
...,...,...,...,...,...,...,...
401,4.6,"1,014 Ratings",8% off,"₹54,900","Apple iPhone 16e (White, 128 GB)",128 GB,Apple
402,4.4,"20,894 Ratings",18% off,"₹17,130","OnePlus Nord CE4 lite 5G (MEGA BLUE, 128 GB) ...",128 GB,Qualcomm
403,4.2,"2,635 Ratings",24% off,"₹16,154","Samsung Galaxy A16 5G (Blue Black, 128 GB) (8...",128 GB,Mediatek
404,4.4,"8,969 Ratings",28% off,"₹17,999","Infinix Note 50s 5G+ (Titanium Grey, 256 GB) ...",256 GB,Mediatek
405,4.4,"26,715 Ratings",33% off,"₹19,999","Motorola Edge 50 Neo (PANTONE Poinciana, 256 G...",256 GB,Mediatek

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 388 entries, 0 to 405
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   star       388 non-null    float64
 1   rating     388 non-null    object
 2   discount   388 non-null    object
 3   price      388 non-null    object
 4   brand      388 non-null    object
 5   storage    388 non-null    object
 6   processor  388 non-null    object
dtypes: float64(1), object(6)
memory usage: 24.2+ KB

In [74]:
df.replace({
    'rating' : ('[Ratings]','[,]'),
    'price' : ('[₹]','[,]')
},'',regex=True,inplace=True)
df

,star,rating,discount,price,brand,storage,processor
0,4.2,50094,20% off,9999,"MOTOROLA g35 5G (Guava Red, 128 GB) (4 GB RAM)",128 GB,Unisoc
1,4.5,58286,22% off,13999,"vivo T4x 5G (Marine Blue, 128 GB) (6 GB RAM)",128 GB,Mediatek
2,4.3,166171,20% off,11999,"Motorola g45 5G (Brilliant Blue, 128 GB) (8 G...",128 GB,Snapdragon
3,4.2,51771,37% off,6249,"Samsung Galaxy F05 (Twilight Blue, 64 GB) (4 ...",64 GB,Mediatek
4,4.5,58286,22% off,13999,"vivo T4x 5G (Pronto Purple, 128 GB) (6 GB RAM)",128 GB,Mediatek
...,...,...,...,...,...,...,...
401,4.6,1014,8% off,54900,"Apple iPhone 16e (White, 128 GB)",128 GB,Apple
402,4.4,20894,18% off,17130,"OnePlus Nord CE4 lite 5G (MEGA BLUE, 128 GB) ...",128 GB,Qualcomm
403,4.2,2635,24% off,16154,"Samsung Galaxy A16 5G (Blue Black, 128 GB) (8...",128 GB,Mediatek
404,4.4,8969,28% off,17999,"Infinix Note 50s 5G+ (Titanium Grey, 256 GB) ...",256 GB,Mediatek
405,4.4,26715,33% off,19999,"Motorola Edge 50 Neo (PANTONE Poinciana, 256 G...",256 GB,Mediatek

In [75]:
df['brand'] = df['brand'].replace(r'\s*\(.*?\)\s*', '', regex=True)
df

,star,rating,discount,price,brand,storage,processor
0,4.2,50094,20% off,9999,MOTOROLA g35 5G,128 GB,Unisoc
1,4.5,58286,22% off,13999,vivo T4x 5G,128 GB,Mediatek
2,4.3,166171,20% off,11999,Motorola g45 5G,128 GB,Snapdragon
3,4.2,51771,37% off,6249,Samsung Galaxy F05,64 GB,Mediatek
4,4.5,58286,22% off,13999,vivo T4x 5G,128 GB,Mediatek
...,...,...,...,...,...,...,...
401,4.6,1014,8% off,54900,Apple iPhone 16e,128 GB,Apple
402,4.4,20894,18% off,17130,OnePlus Nord CE4 lite 5G,128 GB,Qualcomm
403,4.2,2635,24% off,16154,Samsung Galaxy A16 5G,128 GB,Mediatek
404,4.4,8969,28% off,17999,Infinix Note 50s 5G+,256 GB,Mediatek
405,4.4,26715,33% off,19999,Motorola Edge 50 Neo,256 GB,Mediatek

In [76]:
df.price=df.price.astype(int)
df.price.dtype

dtype('int64')

In [77]:
df.rating=df.rating.astype(int)
df.rating.dtype

dtype('int64')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 388 entries, 0 to 405
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   star       388 non-null    float64
 1   rating     388 non-null    int64
 2   discount   388 non-null    object
 3   price      388 non-null    int64
 4   brand      388 non-null    object
 5   storage    388 non-null    object
 6   processor  388 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 24.2+ KB

In [79]:
df

,star,rating,discount,price,brand,storage,processor
0,4.2,50094,20% off,9999,MOTOROLA g35 5G,128 GB,Unisoc
1,4.5,58286,22% off,13999,vivo T4x 5G,128 GB,Mediatek
2,4.3,166171,20% off,11999,Motorola g45 5G,128 GB,Snapdragon
3,4.2,51771,37% off,6249,Samsung Galaxy F05,64 GB,Mediatek
4,4.5,58286,22% off,13999,vivo T4x 5G,128 GB,Mediatek
...,...,...,...,...,...,...,...
401,4.6,1014,8% off,54900,Apple iPhone 16e,128 GB,Apple
402,4.4,20894,18% off,17130,OnePlus Nord CE4 lite 5G,128 GB,Qualcomm
403,4.2,2635,24% off,16154,Samsung Galaxy A16 5G,128 GB,Mediatek
404,4.4,8969,28% off,17999,Infinix Note 50s 5G+,256 GB,Mediatek
405,4.4,26715,33% off,19999,Motorola Edge 50 Neo,256 GB,Mediatek

In [80]:
df.storage.unique()

array(['128 GB', '64 GB', '256 GB', '4 MB', '32 MB', '512 GB', '64 MB',
       '16 GB'], dtype=object)

In [81]:
df

,star,rating,discount,price,brand,storage,processor
0,4.2,50094,20% off,9999,MOTOROLA g35 5G,128 GB,Unisoc
1,4.5,58286,22% off,13999,vivo T4x 5G,128 GB,Mediatek
2,4.3,166171,20% off,11999,Motorola g45 5G,128 GB,Snapdragon
3,4.2,51771,37% off,6249,Samsung Galaxy F05,64 GB,Mediatek
4,4.5,58286,22% off,13999,vivo T4x 5G,128 GB,Mediatek
...,...,...,...,...,...,...,...
401,4.6,1014,8% off,54900,Apple iPhone 16e,128 GB,Apple
402,4.4,20894,18% off,17130,OnePlus Nord CE4 lite 5G,128 GB,Qualcomm
403,4.2,2635,24% off,16154,Samsung Galaxy A16 5G,128 GB,Mediatek
404,4.4,8969,28% off,17999,Infinix Note 50s 5G+,256 GB,Mediatek
405,4.4,26715,33% off,19999,Motorola Edge 50 Neo,256 GB,Mediatek

In [82]:
df.to_csv("flikpart_cleaned data",index=False)